server:
  port: 8001
spring:
  shardingsphere:
    datasource:
      names: m1,m2,m3
      m1:
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: Changeme_123
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.3.50:3306/test_db?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        hikari:
          # 连接池中允许的最小连接数。缺省值：10
          minimum-idle: 10
          # 连接池中允许的最大连接数。缺省值：10
          maximum-pool-size: 100
          # 自动提交
          auto-commit: true
          # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
          connection-timeout: 3000000
          # 数据库连接测试语句
          connection-test-query: SELECT 1
      m2:
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: Changeme_123
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.3.49:3306/test_db?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        hikari:
          # 连接池中允许的最小连接数。缺省值：10
          minimum-idle: 10
          # 连接池中允许的最大连接数。缺省值：10
          maximum-pool-size: 100
          # 自动提交
          auto-commit: true
          # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
          connection-timeout: 3000000
          # 数据库连接测试语句
          connection-test-query: SELECT 1
      m3:
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: Changeme_123
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.3.46:3306/test_db?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        hikari:
          # 连接池中允许的最小连接数。缺省值：10
          minimum-idle: 10
          # 连接池中允许的最大连接数。缺省值：10
          maximum-pool-size: 100
          # 自动提交
          auto-commit: true
          # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
          connection-timeout: 3000000
          # 数据库连接测试语句
          connection-test-query: SELECT 1
    rules:
      sharding:
        tables:
          t_user:
            actual-data-nodes: m$->{1..3}.t_user
            database-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: db_line
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
          t_user_detail:
            actual-data-nodes: m$->{1..3}.t_user_detail
            database-strategy:
              complex:
                sharding-columns: id,user_id
                sharding-algorithm-name: db_complex_line
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker:
                id: 1023
        sharding-algorithms:
          db_complex_line:
            type: CLASS_BASED
            props:
              strategy: complex
              algorithmClassName: com.jaay.gene.demo.algorithm.GeneComplexAlgorithm
          db_line:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.jaay.gene.demo.algorithm.GeneStandardAlgorithm
    props:
      show-sql: true
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.jaay.gene.demo.pojo
